# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc676812e26e1dc8869077ae46f93fc82656fc981a4554a561912915cfbb94a05f4745d1c15f5e82282b3cf1ac181064220cb6d40515d424e02366d49f720d1a

test:
  secret_key_base: 3f73a9fe5befade35d78cf3149e78f4e97e84326a4e1939dfc37eb1d1c4c882d8b81f084f03d63f7c669876f3c855ba8cfcc6feca5c7c4e73934dbf7367ca672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
